### ISSUE TITLE
Player Leaderboard Broken

### ISSUE THREAD

**Issue by Thaldoras** [BlauhausTechnology/MoonbaseIssues#16] opened 2019-02-27 05:57 UTC
The player leaderboard has stopped updating.

The alliance menu shows the correct scores of the players in the alliance. Take note of Ebon Hawk and Rey's scores.

![whatsapp image 2019-02-26 at 23 05 13 1](https://user-images.githubusercontent.com/13771433/53469014-0c101800-3a65-11e9-9f70-9490228df0b0.jpeg)

Below you can see that Ebon Hawk should be a higher rank than Rey.

![whatsapp image 2019-02-26 at 23 05 13](https://user-images.githubusercontent.com/13771433/53469023-0e727200-3a65-11e9-8b4c-cb52b4c4d9b0.jpeg)

**Comment by freever** [comment] 2019-02-27 06:14
Confirmed. Scores in the database are indeed out of whack with rankings. Restarting the server will probably fix it but I need to do some digging to find out what it's happening.

**Comment by freever** [comment] 2019-03-07 09:21
This is probably due to a connection drop between the game itself and the central server. I've taken steps to resolve it, so let's hope this is now fixed...

**Closed by freever** 2019-03-07 09:21 UTC
Labels: bug, fixed
