### ISSUE TITLE
UI shows wrong available troop count when preparing an attack

### ISSUE THREAD

**Issue by ioneethling** [BlauhausTechnology/MoonbaseIssues#9] opened 2019-02-24 04:10 UTC
Sometimes when you send out an attack it shows you've launched one attack with the timer, but the units don't leave according to the UI, but when you then try launch it shows insufficient units for attack, logging this because it could potentially be leading to an issue where your units don't return to base after an attack, but I can't be sure. What also happens is when I go back to home screen it also shows that the units are still there for a while.

**Comment by freever** [comment] 2019-02-24 06:38
duplicate of #10

**Closed by freever** 2019-02-24 06:38 UTC
Labels: duplicate
